name: Mayumy_Service_App
description: A new Flutter project.

environment:
  sdk: ">=2.19.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
dev_dependencies:
  flutter_lints: ^4.0.0
